### ISSUE TITLE
Use @types/rascal

### ISSUE THREAD

**Issue by Zehelein** [zijin-m/-zijin-m-rascal#1]
First off: thanks for this nice wrapper around rascal. I was just starting to think on how to wrap the async rascall calls nicely into classes - but you did that already in a very nice way.

One thing that I noticed is that you have your own rascal ts definition. Since a month there is a kind of "official" one around: https://www.npmjs.com/package/@types/rascal

I played around a bit and noticed too late to create a PR in time - but it is anyways not a big change (https://github.com/Zehelein/-zijin-m-rascal/commit/331f4fb30e3752fa2344cd265ca9c11cd20f5c97)

And I have one additional question about the usage of EventEmitter. If I start a publisher to publish one message per second. And then stop the RabbitMQ I get the EventEmitter 

(node:25808) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 paused listeners added to [Vhost]. Use emitter.setMaxListeners() to increase limit

Does it make sense to proactively increase this limit? I did not really dig into it deep. When I started RabbitMQ again all the queued publish events were correctly sent to RabbitMQ so this is fine. Or would there be an option to apply some back-pressure and not accept any more publish messages/wait for prolonged times?

**Comment by zijin-m** [comment]
thx,updated
